image: python:3.6
stages:
  - deploy
deploy:
  stage: deploy
  before_script:
    - apt-get update -qy
    - apt-get install -y python3 python3-pip ruby-sass locales rsync
    - echo "en_US UTF-8" > /etc/locale.gen
    - locale-gen en_US.UTF-8
    - export LANG=en_US.UTF-8
    - export LANGUAGE=en_US:en
    - export LC_ALL=en_US.UTF-8
    - export PYTHONPATH=.:$PYTHONPATH
  script:
    - if [ ! -n "$SERVER_SSH_KEY" ]; then exit 0; fi
    - mkdir ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SERVER_SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - pip3 install -r requirements.txt
    - make prod
    - echo "Deploying $CI_COMMIT_REF_NAME..."
    - if [ "$CI_COMMIT_REF_NAME" = "master" ]; then export DIRECTORY=gdpr-portal-master; fi;
    - if [ "$CI_COMMIT_REF_NAME" = "staging" ]; then export DIRECTORY=gdpr-portal-staging; fi;
    - if [ -n "$DIRECTORY" ]; then rsync --progress -r -e "ssh -o StrictHostKeyChecking=no -o identityFile=~/.ssh/id_rsa" build/* ${SERVER_SSH_USER}@${SERVER_SSH_IP}:${SERVER_SSH_DIRECTORY}/$DIRECTORY --delete; fi;
